loss_weights:              # Weights of different loss, 0 means ignoring that loss
    point_to_point: 1      # Point to point distance
    coupling: 1            # Coupling loss between initial SMPL estimation and the final results
    chamfer: 1             # Chamfer loss
    shape_reg: 1           # Shape regularizer
    pose_reg: 1            # Pose regularizer

max_iter: 1000             # Maximum steps of optimization
term_tol: 1                # Termination tolerance
