device: cuda              # Run on GPU (cuda) or CPU (cpu)

smpl:                     # SMPL related assets
  model_path: data/smpl
  gender: neutral
  num_body_joints: 23
  joint_regressor_extra: data/smpl/SMPL_to_J19.pkl
  mean_params: data/smpl/smpl_mean_params.npz
  mesh: data/smpl/smpl_example_mesh.obj

body_model: smpl

smpl_loss_weights:        # Weights of different loss, 0 means ignoring that loss
    chamfer: 1            # Chamfer loss

optimize_lbs: True        # If lbs of the point cloud is also optimized

max_iter: 10000           # Maximum steps of ICP
lr: 5e-3                  # Learning rate
ftol: 1e-9                # Relative loss change tolerance.
gtol: 1e-9                # Absolute gradient value tolerance.
