device: cuda              # Run on GPU (cuda) or CPU (cpu)

smpl:                     # SMPL related assets
  model_path: data/smpl
  gender: neutral
  num_body_joints: 23
  joint_regressor_extra: data/smpl/SMPL_to_J19.pkl
  mean_params: data/smpl/smpl_mean_params.npz
  mesh: data/smpl/smpl_example_mesh.obj

body_model: smpld                 # Body model, support smpl or smpld

smpl_loss_weights:                # Weights of different loss, 0 means ignoring that loss
    chamfer: 1                   # Coupling loss between initial SMPL estimation and the final results

smpld_loss_weights:               # Weights of different loss for optimizing details
    chamfer: 1                    # Chamfer loss
    coupling: 1                   # Coupling loss between initial SMPL estimation and the final results
    laplacian: 0.2                # Laplacian smoothing loss
    normal_consistency: 0.001     # Neighboring face normal consistency loss

renderer:
    cam_trans: [0, -0.5, 2]       # camera translation
    image_size: 512               # rendered image size

max_iter: 3000                    # Maximum steps of ICP
lr: 1e-3                          # Learning rate
ftol: 1e-9                        # Relative loss change tolerance.
gtol: 1e-9                        # Absolute gradient value tolerance.
