smpl:                     # SMPL related assets
  model_path: data/smpl
  gender: neutral
  num_body_joints: 23
  joint_regressor_extra: data/smpl/SMPL_to_J19.pkl
  mean_params: data/smpl/smpl_mean_params.npz
  mesh: data/smpl/smpl_example_mesh.obj

body_model: smpld                 # Body model, support smpl or smpld

loss_weights:                     # Weights of different loss, 0 means ignoring that loss
    # point_to_mesh: 1            # Point to plane distance
    coupling: 1                 # Coupling loss between initial SMPL estimation and the final results
    chamfer: 1                    # Chamfer loss
    laplacian: 0.2               # Laplacian smoothing loss
    normal_consistency: 0.001     # Neighboring face normal consistency loss
    # shape_reg: 1                # Shape regularizer
    # pose_reg: 1                 # Pose regularizer

max_iter: 3000                    # Maximum steps of ICP
lr: 1e-3                          # Learning rate
ftol: 1e-9                        # Relative loss change tolerance.
gtol: 1e-9                        # Absolute gradient value tolerance.
